// 宏定义--大写+下划线

// initial_address = 32'h0000_3000
`define INIT_ADDR 32'h0000_3000

// path
`define PATH_INSTR "./code.txt"   // path of instructions
`define PATH_DATA "./data.txt"    // path of data

// size
`define SIZE_INSTR      1023     // size of instructions
`define SIZE_DATA       1023     // size of data
`define SIZE_ALUOP      2        // size of ALUOP
`define SIZE_ALUCTRLOUT 3        // size of AluCtrlOut

// //just for easy
// `define SIGNAL {RegDst, Jump, Branch, MemRead, MemtoReg, ALUOp, MemWrite, ALUSrc, RegWrite, ExtOp}

// op
`define OP_R     6'b000000
`define OP_ADDIU 6'b001000
`define OP_ADDI  6'b001001 
`define OP_BEQ   6'b000100
`define OP_J     6'b000010
`define OP_LUI   6'b001111
`define OP_LW    6'b100011
`define OP_ORI   6'b001101
`define OP_SW    6'b101011

// funct
`define FUNCT_ADD  6'b100000
`define FUNCT_AND  6'b100100
`define FUNCT_OR   6'b100101
`define FUNCT_SLT  6'b101010
`define FUNCT_SUB  6'b100010
`define FUNCT_XOR  6'b100110
// added 2022.12.16
`define FUNCT_SLL  6'b000000
`define FUNCT_SLLV 6'b000100
`define FUNCT_SRL  6'b000010
`define FUNCT_SRLV 6'b000110
`define FUNCT_SRA  6'b000011
`define FUNCT_SRAV 6'b000111

//ALUOp -- generated by ALUCtrlOut last 3 digits
`define ALUOP_R         3'b000  // defined by myself

`define ALUOP_ADD       3'b010 
`define ALUOP_ADDIU     3'b010 
`define ALUOP_ADDI      3'b010
`define ALUOP_LW        3'b010
`define ALUOP_SW        3'b010

`define ALUOP_SUB       3'b110
`define ALUOP_BEQ       3'b110

`define ALUOP_LUI       3'b100

`define ALUOP_OR        3'b001
`define ALUOP_ORI       3'b001

`define ALUOP_J         3'b111  // defined by myself

`define ALUOP_0         3'b101  // defined by myself -- Flush instruction

//ALUCtrlOut
`define ALUCTRLOUT_ADD   4'b0010 
`define ALUCTRLOUT_ADDIU 4'b0010 //下面四个其实没有，就是为了代码对应方便，本质上只有ALUCTRLOUT_ADD
`define ALUCTRLOUT_ADDI  4'b0010 
`define ALUCTRLOUT_LW    4'b0010 
`define ALUCTRLOUT_SW    4'b0010 

`define ALUCTRLOUT_SUB   4'b0110
`define ALUCTRLOUT_BEQ   4'b0110 // same as ALUCTRLOUT_ADD

`define ALUCTRLOUT_AND   4'b0000

`define ALUCTRLOUT_OR    4'b0001
`define ALUCTRLOUT_ORI   4'b0001 // same as ALUCTRLOUT_ADD

`define ALUCTRLOUT_XOR   4'b0011 // defined by myself
`define ALUCTRLOUT_LUI   4'b0100 // defined by myself
`define ALUCTRLOUT_SLT   4'b0111

// add
`define ALUCTRLOUT_SLL   4'b0000
`define ALUCTRLOUT_SLLV  4'b0000
`define ALUCTRLOUT_SRL   4'b0000
`define ALUCTRLOUT_SRLV  4'b0000
`define ALUCTRLOUT_SRA   4'b0000
`define ALUCTRLOUT_SRAV  4'b0000